# Generated by Django 4.1.3 on 2022-12-05 15:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Den vyzvednutí')),
                ('delivery', models.CharField(max_length=30, verbose_name='Místo výdeje')),
                ('part', models.CharField(max_length=20, verbose_name='Část dne')),
                ('ordering', models.PositiveSmallIntegerField(verbose_name='řazení')),
                ('alive_fish', models.BooleanField(verbose_name='Možnost odebrat živou rybu')),
            ],
            options={
                'verbose_name': 'Místo a čas výdeje',
                'verbose_name_plural': 'Místa a čas výdeje',
                'ordering': ('ordering', 'day', 'part', 'delivery'),
                'unique_together': {('day', 'delivery', 'part')},
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=100, verbose_name='Procedura')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Zpracování',
                'verbose_name_plural': 'Zpracování',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=30, verbose_name='Ryba')),
                ('desc', models.CharField(max_length=30, verbose_name='Popis')),
                ('price_alive', models.PositiveSmallIntegerField(default=0, verbose_name='Cena živá váha (pouze na stánku)')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Cena kuchaná ryba')),
                ('store', models.IntegerField(default=0, verbose_name='zásoba')),
                ('cons', models.BooleanField(default=False, verbose_name='Nutnost konsultace')),
            ],
            options={
                'verbose_name': 'Ryba',
                'verbose_name_plural': 'Ryby',
                'ordering': ['fish', 'desc'],
                'unique_together': {('fish', 'desc')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Jméno')),
                ('surname', models.CharField(max_length=60, verbose_name='Příjmení')),
                ('email', models.EmailField(blank=True, help_text='nepovinné', max_length=254, null=True, verbose_name='Email')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon')),
                ('commercial', models.BooleanField(verbose_name='Reklamní účely')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'formulář vyplněn'), (1, 'objednáno'), (2, 'připraveno'), (3, 'odeslána informační SMS'), (4, 'vyřízeno'), (5, 'odeslané platební údaje na email'), (99, 'zrušeno')], default=0)),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka')),
                ('adress', models.CharField(blank=True, help_text='nepovinné', max_length=255, null=True, verbose_name='Adresa')),
                ('alive_fish', models.BooleanField(default=False, verbose_name='Platba za živou váhu')),
                ('package', models.BooleanField(default=False, help_text='Chci připravit balíček a dostat SMS, že je na stánku vše připraveno.', verbose_name='balíček')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.delivery', verbose_name='Místo a čas výdeje')),
            ],
            options={
                'verbose_name': 'Objednávka',
                'verbose_name_plural': 'Objednávky',
                'ordering': ('pk', 'surname'),
            },
        ),
        migrations.CreateModel(
            name='OrderFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Množství')),
                ('desc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Poznámka')),
                ('weight', models.FloatField(default=0, help_text='Po vyplnění váhy bude dopočítána cena', verbose_name='Váha')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fish', to='orders.finish', verbose_name='Zpracování')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_fish', to='orders.fish', verbose_name='Ryba')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_fish', to='orders.order', verbose_name='objednávka')),
            ],
            options={
                'verbose_name': 'Objednaná ryba',
                'verbose_name_plural': 'Objednané ryby',
            },
        ),
    ]
