# Generated by Django 4.1.4 on 2022-12-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfish',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka'),
        ),
    ]
