# Generated by Django 5.1.4 on 2024-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderfish_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fish",
            name="price_alive",
        ),
        migrations.AlterField(
            model_name="fish",
            name="price",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Cena živá váha"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="alive_fish",
            field=models.BooleanField(
                default=False,
                verbose_name="Chci živou rybu a vyzvednu si jí v Lišově na stánku",
            ),
        ),
    ]
