# Generated by Django 5.1.4 on 2024-12-08 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_fish_price_alive_alter_fish_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_code",
                    models.CharField(max_length=255, verbose_name="Slevový kód"),
                ),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        help_text="Hodnota musí být mezi 0 a 100.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="voucher",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "objednáno"),
                    (2, "připraveno"),
                    (3, "odeslána informační SMS"),
                    (4, "vyřízeno"),
                    (5, "odeslané platební údaje na email"),
                ],
                default=1,
            ),
        ),
    ]
