# Generated by Django 5.1.4 on 2024-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_voucher_order_voucher_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="voucher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
