# Generated by Django 5.1.4 on 2024-12-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Název slevy, např. 'Letní akce'", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Popis slevy nebo podmínky"),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Procento slevy, např. 10.50 pro 10.5% slevu",
                        max_digits=5,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Datum a čas začátku slevy"),
                ),
                ("end_date", models.DateTimeField(help_text="Datum a čas konce slevy")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indikuje, zda je sleva aktivní"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sleva",
                "verbose_name_plural": "Slevy",
                "ordering": ["start_date"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "formuář vyplněn"),
                    (1, "objednáno"),
                    (2, "připraveno"),
                    (3, "odeslána informační SMS"),
                    (4, "odeslané platební údaje na email a SMS"),
                    (5, "vyřízeno"),
                ],
                default=1,
            ),
        ),
    ]
