# Generated by Django 5.1.4 on 2024-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_discountperiod_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Procento slevy, např. 10.50 pro 10.5% slevu",
                max_digits=5,
            ),
        ),
    ]
