# Generated by Django 5.1.4 on 2024-12-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_processedby_order_processed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Procento slevy, např. 10.50 pro 10.5% slevu",
                max_digits=5,
                verbose_name="Sleva",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.processedby",
                verbose_name="Zpracování",
            ),
        ),
        migrations.AlterField(
            model_name="processedby",
            name="processed_by",
            field=models.CharField(max_length=30, verbose_name="Zpracování"),
        ),
    ]
