# Generated by Django 5.1.4 on 2024-12-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="enable",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
