# Generated by Django 5.1.4 on 2024-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_delivery_enable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="enable",
            field=models.BooleanField(default=True, verbose_name="Zapnuto"),
        ),
    ]
